<<<<<<< HEAD
# Generated by Django 3.2 on 2021-04-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_squirrel1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel1',
            name='Borough_Boundaries',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='City_Council_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Community_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Police_Precincts',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='X',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Y',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Zip_Codes',
        ),
        migrations.AddField(
            model_name='squirrel1',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='squirrel1',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Above_Ground_Sighter_Measurement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?'), ('', '')], default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Approaches',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Chasing',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Climbing',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Color_Notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Combination_Fur',
            field=models.CharField(default='+', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Eating',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Foraging',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Hectare',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Hectare_Squirrel_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Indifferent',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Kuks',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Lat_Long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Location',
            field=models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Moans',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Other_Activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Other_Interactions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnammon', 'Cinnammon'), ('', '')], default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Quaas',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Running',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Runs_From',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Specific_Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Tail_Flags',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Tail_Twitches',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
=======
# Generated by Django 3.2 on 2021-04-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_squirrel1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel1',
            name='Borough_Boundaries',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='City_Council_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Community_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Police_Precincts',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='X',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Y',
        ),
        migrations.RemoveField(
            model_name='squirrel1',
            name='Zip_Codes',
        ),
        migrations.AddField(
            model_name='squirrel1',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='squirrel1',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Above_Ground_Sighter_Measurement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('?', '?'), ('', '')], default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Approaches',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Chasing',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Climbing',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Color_Notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Combination_Fur',
            field=models.CharField(default='+', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Eating',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Foraging',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Hectare',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Hectare_Squirrel_Number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Indifferent',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Kuks',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Lat_Long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Location',
            field=models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Moans',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Other_Activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Other_Interactions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnammon', 'Cinnammon'), ('', '')], default='', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Quaas',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Running',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Runs_From',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Specific_Location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Tail_Flags',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Tail_Twitches',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel1',
            name='Unique_Squirrel_ID',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
>>>>>>> d4b35acf0fc875078ef573a2c8764e055609208a
