# Generated by Django 3.2 on 2021-04-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210414_0001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
