# Generated by Django 3.2 on 2021-04-15 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_squirrel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='X',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Y',
            new_name='Longitude',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Borough_Boundaries',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='City_Council_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Community_Districts',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Police_Precincts',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Zip_Codes',
        ),
    ]
