<<<<<<< HEAD
# Generated by Django 3.2 on 2021-04-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210415_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
        migrations.AddField(
            model_name='squirrelmodel',
            name='Indifferent',
            field=models.CharField(choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=200, null=True),
        ),
    ]
=======
# Generated by Django 3.2 on 2021-04-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210415_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
        migrations.AddField(
            model_name='squirrelmodel',
            name='Indifferent',
            field=models.CharField(choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=200, null=True),
        ),
    ]
>>>>>>> d4b35acf0fc875078ef573a2c8764e055609208a
